### ISSUE TITLE
[Feature] 1.21 Compatibility?

### ISSUE THREAD

**Issue by Etanarvazac** [Aton-Kish/your-reputation#44]
### Describe the solution you'd like

I am looking to see if this mod will be updated to 1.21.

**Comment by Aton-Kish** [comment]
From Minecraft 1.21+, I separated the mod project.

- WTHIT
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-wthit
  - modrinth: https://modrinth.com/mod/your-reputation-wthit
- Jade
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-jade
  - modrinth: https://modrinth.com/mod/your-reputation-jade

This is due to issues #33 #34 .

**Comment by Etanarvazac** [comment]
> From Minecraft 1.21+, I separated the mod project.
> 
> * WTHIT
>   
>   * curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-wthit
>   * modrinth: https://modrinth.com/mod/your-reputation-wthit
> * Jade
>   
>   * curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-jade
>   * modrinth: https://modrinth.com/mod/your-reputation-jade
> 
> This is due to issues #33 #34 .

I do apologize for seeing this only now. Thank you for the update!
